-- Commands.lua
-- Completion Navigator :: slash command dispatcher and built-in commands.
--
-- To add a command, do NOT edit this file. In the owning module call:
--
--   CN:RegisterCommand{
--       name    = "example",
--       args    = "<id>",
--       help    = "Does the example thing.",
--       order   = 50,
--       handler = function(args) ... end,
--   }
--
-- Help output and dispatch pick it up automatically.

local ADDON_NAME, CN = ...

local Print = CN.Print

------------------------------------------------------------
-- HELP
------------------------------------------------------------

local function ShowHelp()
    Print("Commands:")

    local sorted = {}

    for _, definition in ipairs(CN.commandList) do
        table.insert(sorted, definition)
    end

    table.sort(sorted, function(a, b)
        if a.order == b.order then
            return a.name < b.name
        end

        return a.order < b.order
    end)

    for _, definition in ipairs(sorted) do
        local line = "|cffffff00/cn " .. definition.name

        if definition.args and definition.args ~= "" then
            line = line .. " " .. definition.args
        end

        line = line .. "|r"

        if definition.help and definition.help ~= "" then
            line = line .. " - " .. definition.help
        end

        Print(line)
    end
end

CN.ShowHelp = ShowHelp

------------------------------------------------------------
-- STATUS
------------------------------------------------------------

local function ShowStatus()
    Print("Version " .. CN.version .. " is loaded.")

    if CN.character then
        Print("Active character: "
            .. tostring(CN.character.name or "Unknown")
            .. " (Level " .. tostring(CN.character.level or "?") .. ")")
    end

    local settings = CN.Settings()

    if settings then
        Print("Priority mode: " .. tostring(settings.priorityMode))
        Print("Debug mode: " .. (settings.debug and "enabled" or "disabled"))
    end

    Print("Known characters: " .. CN.GetCharacterCount())

    local moduleNames = {}

    for name in pairs(CN.modules) do
        table.insert(moduleNames, name)
    end

    table.sort(moduleNames)

    if #moduleNames > 0 then
        Print("Modules: " .. table.concat(moduleNames, ", "))
    end
end

CN.ShowStatus = ShowStatus

------------------------------------------------------------
-- DISPATCHER
------------------------------------------------------------

local function HandleSlashCommand(message)
    message = CN.Trim(message)

    local command, arguments = message:match("^(%S*)%s*(.-)$")

    command   = string.lower(command or "")
    arguments = CN.Trim(arguments)

    if command == "" then
        ShowStatus()
        return
    end

    local definition = CN.commands[command]

    if definition then
        local ok, err = pcall(definition.handler, arguments)

        if not ok then
            Print("Error in /cn " .. command .. ": " .. tostring(err))
        end

        return
    end

    Print("Unknown command: " .. tostring(command))

    ShowHelp()
end

CN.HandleSlashCommand = HandleSlashCommand

------------------------------------------------------------
-- REGISTRATION
------------------------------------------------------------

SLASH_COMPLETIONNAVIGATOR1 = "/cn"
SLASH_COMPLETIONNAVIGATOR2 = "/completionnavigator"

SlashCmdList.COMPLETIONNAVIGATOR = HandleSlashCommand

------------------------------------------------------------
-- BUILT-IN COMMANDS
------------------------------------------------------------

CN:RegisterCommand{
    name    = "status",
    order   = 1,
    help    = "Show addon status.",
    handler = function()
        ShowStatus()
    end,
}

CN:RegisterCommand{
    name    = "help",
    order   = 2,
    help    = "Show this help.",
    handler = function()
        ShowHelp()
    end,
}

CN:RegisterCommand{
    name    = "debug",
    order   = 3,
    help    = "Toggle debug mode.",
    handler = function()
        local settings = CN.Settings()

        settings.debug = not settings.debug

        Print("Debug mode " .. (settings.debug and "enabled." or "disabled."))
    end,
}

CN:RegisterCommand{
    name    = "mode",
    args    = "[modeName]",
    order   = 4,
    help    = "Show or set the priority mode.",
    handler = function(args)
        local settings = CN.Settings()

        if args == "" then
            Print("Priority mode: " .. tostring(settings.priorityMode))
            Print("Available: " .. table.concat(CN.priorityModes, ", "))
            return
        end

        local requested = string.lower(args)

        for _, mode in ipairs(CN.priorityModes) do
            if mode == requested then
                settings.priorityMode = requested
                Print("Priority mode set to " .. requested .. ".")
                return
            end
        end

        Print("Unknown priority mode: " .. requested)
        Print("Available: " .. table.concat(CN.priorityModes, ", "))
    end,
}
