-- Commands.lua
-- Completion Navigator :: slash command dispatcher and built-in commands.
--
-- To add a command, do NOT edit this file. In the owning module call:
--
--   CN:RegisterCommand{
--       name    = "example",
--       args    = "<id>",
--       help    = "Does the example thing.",
--       order   = 50,
--       handler = function(args) ... end,
--   }
--
-- Help output and dispatch pick it up automatically.

local ADDON_NAME, CN = ...

local Print = CN.Print

------------------------------------------------------------
-- HELP
------------------------------------------------------------

-- ONE FLAT LIST OF 120 COMMANDS IS A LIST NOBODY READS.
--
-- Help printed every command in registration order, which was fine at twelve
-- and is useless at a hundred and twenty: the answer to "what can this thing
-- do?" scrolled past in a wall of yellow, and the commands people actually
-- needed were indistinguishable from the diagnostics.
--
-- Three changes, none of them clever:
--
--   * A SHORT list by default -- the dozen things worth knowing on day one.
--   * `/cn help all` for the whole thing, grouped.
--   * `/cn help <word>` searches names and descriptions, because somebody
--     who half-remembers "the one about lockouts" should not have to read a
--     hundred and twenty lines to find `/cn instances`.
CN.helpEssentials = {
    "", "next", "go", "why", "order", "plan", "follow", "zone", "nearby",
    "chase", "mode", "show", "ui", "setup", "selftest",
}

-- Groups, by what the player is trying to do rather than by which module
-- happens to own the command.
CN.helpGroups = {
    { title = "Deciding what to do",
      names = { "next", "why", "order", "plan", "mode", "show", "learned",
                "situation", "goal", "chase" } },
    { title = "Getting there",
      names = { "go", "travel", "nav", "navdiag", "arrow", "calibrate",
                "pins", "follow", "zone", "nearby", "where am i" } },
    { title = "What is left",
      names = { "progress", "loremaster", "zones", "available", "waiting",
                "breakdown", "vault", "instances", "drops", "clock", "bags",
                "orders", "alts" } },
    { title = "Setting it up",
      names = { "setup", "ui", "scale", "colourblind", "hud", "cues",
                "locale", "welcome" } },
    { title = "When something is wrong",
      names = { "selftest", "errors", "dbsize", "capture", "contribute",
                "harvest", "debug" } },
}

local function PrintCommand(definition, indent)
    local line = (indent or "") .. "|cffffff00/cn " .. definition.name

    if definition.args and definition.args ~= "" then
        line = line .. " " .. definition.args
    end

    line = line .. "|r"

    if definition.help and definition.help ~= "" then
        line = line .. " - " .. definition.help
    end

    Print(line)
end

local function Find(name)
    for _, definition in ipairs(CN.commandList) do
        if definition.name == name then
            return definition
        end
    end

    return nil
end

local function ShowEssentials()
    Print("The ones worth knowing:")

    for _, name in ipairs(CN.helpEssentials) do
        local definition = Find(name)

        if definition then
            PrintCommand(definition, "  ")
        end
    end

    Print("|cff999999" .. #CN.commandList .. " commands in total. "
        .. "|cffffff00/cn help all|r lists them by what they are for, and "
        .. "|cffffff00/cn help <word>|r searches them.|r")
end

local function SearchHelp(term)
    term = string.lower(term)

    local matches = {}

    for _, definition in ipairs(CN.commandList) do
        local haystack = string.lower(definition.name .. " "
            .. tostring(definition.help or ""))

        if haystack:find(term, 1, true) then
            table.insert(matches, definition)
        end
    end

    if #matches == 0 then
        Print("Nothing matches \"" .. term .. "\".")
        Print("|cff999999/cn help all|r lists everything.")
        return
    end

    Print(#matches .. " command(s) matching \"" .. term .. "\":")

    for _, definition in ipairs(matches) do
        PrintCommand(definition, "  ")
    end
end

local function ShowGrouped()
    local shown = {}

    for _, group in ipairs(CN.helpGroups) do
        Print("|cffffd100" .. group.title .. "|r")

        for _, name in ipairs(group.names) do
            local definition = Find(name)

            if definition then
                PrintCommand(definition, "  ")

                shown[name] = true
            end
        end
    end

    local rest = {}

    for _, definition in ipairs(CN.commandList) do
        if not shown[definition.name] then
            table.insert(rest, definition)
        end
    end

    if #rest > 0 then
        table.sort(rest, function(a, b) return a.name < b.name end)

        Print("|cffffd100Everything else|r")

        for _, definition in ipairs(rest) do
            PrintCommand(definition, "  ")
        end
    end
end

local function ShowHelp(args)
    args = CN.Trim(args or "")

    if args ~= "" then
        if string.lower(args) == "all" then
            ShowGrouped()
        else
            SearchHelp(args)
        end

        return
    end

    ShowEssentials()
end

local function ShowFullHelp()
    Print("Commands:")

    local sorted = {}

    for _, definition in ipairs(CN.commandList) do
        table.insert(sorted, definition)
    end

    table.sort(sorted, function(a, b)
        if a.order == b.order then
            return a.name < b.name
        end

        return a.order < b.order
    end)

    for _, definition in ipairs(sorted) do
        local line = "|cffffff00/cn " .. definition.name

        if definition.args and definition.args ~= "" then
            line = line .. " " .. definition.args
        end

        line = line .. "|r"

        if definition.help and definition.help ~= "" then
            line = line .. " - " .. definition.help
        end

        Print(line)
    end
end

CN.ShowHelp     = ShowHelp
CN.ShowFullHelp = ShowFullHelp

------------------------------------------------------------
-- STATUS
------------------------------------------------------------

local function ShowStatus()
    Print("Version " .. CN.version .. " is loaded.")

    if CN.character then
        Print("Active character: "
            .. tostring(CN.character.name or "Unknown")
            .. " (Level " .. tostring(CN.character.level or "?") .. ")")
    end

    local settings = CN.Settings()

    if settings then
        Print("Priority mode: " .. tostring(settings.priorityMode))
        Print("Debug mode: " .. (settings.debug and "enabled" or "disabled"))
    end

    Print("Known characters: " .. CN.GetCharacterCount())

    local moduleNames = {}

    for name in pairs(CN.modules) do
        table.insert(moduleNames, name)
    end

    table.sort(moduleNames)

    if #moduleNames > 0 then
        Print("Modules: " .. table.concat(moduleNames, ", "))
    end
end

CN.ShowStatus = ShowStatus

------------------------------------------------------------
-- DISPATCHER
------------------------------------------------------------

local function HandleSlashCommand(message)
    message = CN.Trim(message)

    local command, arguments = message:match("^(%S*)%s*(.-)$")

    command   = string.lower(command or "")
    arguments = CN.Trim(arguments)

    if command == "" then
        ShowStatus()
        return
    end

    local definition = CN.commands[command]

    if definition then
        local ok, err = pcall(definition.handler, arguments)

        if not ok then
            Print("Error in /cn " .. command .. ": " .. tostring(err))
        end

        return
    end

    Print("Unknown command: " .. tostring(command))

    ShowHelp()
end

CN.HandleSlashCommand = HandleSlashCommand

------------------------------------------------------------
-- REGISTRATION
------------------------------------------------------------

SLASH_COMPLETIONNAVIGATOR1 = "/cn"
SLASH_COMPLETIONNAVIGATOR2 = "/completionnavigator"

SlashCmdList.COMPLETIONNAVIGATOR = HandleSlashCommand

------------------------------------------------------------
-- BUILT-IN COMMANDS
------------------------------------------------------------

CN:RegisterCommand{
    name    = "status",
    order   = 1,
    help    = "Show addon status.",
    handler = function()
        ShowStatus()
    end,
}

CN:RegisterCommand{
    name    = "help",
    args    = "[all, or a word to search for]",
    order   = 2,
    help    = "The commands worth knowing; 'all' for every one.",
    handler = function(args)
        ShowHelp(args)
    end,
}

CN:RegisterCommand{
    name    = "debug",
    order   = 3,
    help    = "Toggle debug mode.",
    handler = function()
        local settings = CN.Settings()

        settings.debug = not settings.debug

        Print("Debug mode " .. (settings.debug and "enabled." or "disabled."))
    end,
}

-- ONE command for "aim the addon", not two.
--
-- 0.28.0 added focus presets -- levelling, collecting, reputation -- which
-- set the weighting AND the type filter together. Registering those as a
-- second command alongside this one would have given the player two things
-- that both mean "what am I doing tonight", differing in ways only the
-- author could explain. So this command absorbed them.
--
-- A preset name applies the preset. A raw profile name still sets just the
-- weighting, exactly as before, because that is what anyone with it in a
-- macro expects.
CN:RegisterCommand{
    name    = "mode",
    aliases = { "focus" },
    args    = "[leveling | collecting | reputation | achievements | professions | everything | off | <profile>]",
    order   = 4,
    help    = "Aim the addon at one kind of play.",
    handler = function(args)
        local settings = CN.Settings()

        local filters = CN:GetModule("Filters")

        local requested = string.lower(CN.Trim(args or ""))

        local function ListOptions()
            local presets = {}

            for name in pairs(CN.modes) do
                table.insert(presets, name)
            end

            table.sort(presets)

            Print("|cff999999Focus: " .. table.concat(presets, ", ") .. "|r")
            Print("|cff999999Weighting only: "
                .. table.concat(CN.priorityModes, ", ") .. "|r")
        end

        if requested == "" then
            local current, active

            if filters then
                current, active = filters.CurrentMode()
            end

            if current and active then
                Print("Focus: |cffffff00" .. active.label .. "|r")
                Print("|cff999999" .. active.note .. "|r")
                Print("|cff999999/cn mode off|r restores what you had before.")
            else
                Print("Priority mode: |cffffff00"
                    .. tostring(settings.priorityMode) .. "|r")
            end

            ListOptions()
            return
        end

        if requested == "off" or requested == "clear" then
            if filters then
                filters.ClearMode()
            end

            Print("Focus cleared. Previous filters and weighting restored.")
            return
        end

        -- A focus preset: weighting and filter together.
        if CN.modes[requested] and filters then
            local ok, preset = filters.ApplyMode(requested)

            if ok then
                Print("Focus: |cffffff00" .. preset.label .. "|r -- "
                    .. preset.note)
                Print("|cff999999/cn mode off|r puts it back.")
                return
            end
        end

        -- A bare profile name: weighting only, unchanged behaviour.
        for _, mode in ipairs(CN.priorityModes) do
            if mode == requested then
                settings.priorityMode = requested

                CN.InvalidateCandidates("mode")

                Print("Priority mode set to |cffffff00" .. requested .. "|r.")
                Print("|cff999999Weighting only; your type filters are "
                    .. "untouched.|r")
                return
            end
        end

        Print("Unknown mode: " .. requested)
        ListOptions()
    end,
}
